name: "Temperton Lab"
description: "This is the official web page for the Temperton Lab at University of Exeter."

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
